### ISSUE TITLE
Tastaturnavigation

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#107]
Soll ermöglicht werden im Inhaltsverzeichnis

**Comment by droda1** [comment]
@JirkaDellOro wollen Sie die Navigation über die Pfeiltasten?
Da hätten wir das Problem, dass wir die Yottube Navigation überschreiben würden die Binds auf k(Wiedergabe), m(mute), pfeiltaste links/rechts(5 sec zurück/vor), c(subtitles) und f(fullscreen) hat.
Können entweder andere nehmen oder ich versuche die Keys irgendwie für das iframe zu disablen und die dann für unsere navigation einzubetten.

**Comment by JirkaDellOro** [comment]
Ich würde annehmen, dass die Youtube-Navigation abhängig vom Fokus ist. Fokussiere ich das Inhaltsverzeichnis, sollte dies navigierbar sein.

**Comment by droda1** [comment]
So ist es auch. Dann setzte ich das um, dass je nach fokus beides funktioniert, danke für die Antwort :)

**Comment by droda1** [comment]
@JirkaDellOro wir haben wenn wir den fokus auf der Navigation haben die Pfeiltasten auf das hochscrollen und runterscrollen innerhalb der Navigation gebindet.
Passt das wenn ich die Tastaturnavigation via Tab und Enter mache?

**Comment by droda1** [comment]
@JirkaDellOro 
habe die Tastaturnavigation jetzt mit 'w' für hoch und 's' für runter implementiert.
Ich hoffe das passt so.

**Comment by JirkaDellOro** [comment]
Tab und Enter ist besser, W und S ist nur für Gamer sinnvoll. Richtig sind die Pfeiltasten und Page up/down für Scrollen
