### ISSUE TITLE
3.7. I-16/24

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#114]
Button fliegt im Bild herum

**Comment by Ahornzweig** [comment]
Ich habe versucht es so gut wie möglich anzupassen. Da ich jedoch keinen Zugang zu Animate habe, ist es nicht komplett richtig.
https://ahornzweig.github.io/Projekt/2018-12-19_16-24_Bit-Farbtiefe_Desktop/2018-12-19_16-24_Bit-Farbtiefe_Desktop_v1.html

**Comment by Ahornzweig** [comment]
Korrekt
