### ISSUE TITLE
5.3. PPI

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#121]
Text rechts schlecht gesetzt. Abstand zwischen Pixel und 4 cm

**Comment by JirkaDellOro** [comment]
Infotext rechts klemmt arg am Bildrand, auch bei anderen Seiten

**Comment by HendrikLange** [comment]
Video ist angepasst, Infotext muss noch überarbeitet werden.

**Comment by droda1** [comment]
@HendrikLange ich kümmer mich drum

**Comment by HendrikLange** [comment]
fixed.
