### ISSUE TITLE
6.4. Reduktion

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#130]
- Das Roboterbild würde besser funktionieren!
- 2 Bit kann so nicht sein.

**Comment by xcluu** [comment]
Es soll in der Interaktion ein 32- und 64bit Bild angezeigt werden, jedoch unterstützen PNG-Dateien nur eine Farbtiefe von bis zu 16bit. Es wäre also durch HTML nicht möglich, 32- und 64bit Bilder anzeigen zu lassen.
Soll ich diese Möglichkeiten also einfach weglassen?

**Comment by xcluu** [comment]
Die Quelle, aus der ich die Information habe, ist hier: https://blender.stackexchange.com/a/153809
Ich war dabei auf der Suche nach einer Möglichkeit, die Render aus blender in 32 Bit zu rendern.

Ich habe nun versucht, eine Zwischenlösung zu suchen, indem die Farbtiefe mit bit pro Pixel referenziert wird, anstatt mit bit pro Kanal. So bin ich zum Ergebnis von 2 bis 48 bit gekommen. (mit Alphakanal wäre das Maximum 64 bit)

**Comment by JirkaDellOro** [comment]
Richtig, man muss beachten, ob von Bit per Pixel oder Bit per Channel gesprochen wird. In deiner Quelle steht:
"Each channel has a sample depth in the range 1 to 16, which is the number of bits used by every sample in the channel."

PNG kann demnach also bis zu 64 Bit pro Pixel
