### ISSUE TITLE
6.9. I-Jpg

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#133]
Warum wäre das Roboterbild hier nicht wenigstens ebenso gut?

**Comment by Ahornzweig** [comment]
Falls das Problem nur an dem Bild liegt, würde ich es dabei belassen.
Die Interaktion ist eine der bereits Vorhandenen und zur Zeit hat keiner von uns Zugriff auf Animate, um das Bild korrekt zu ersetzen.

**Comment by droda1** [comment]
Vor allem hat keiner von uns eine Lizenz

**Comment by JirkaDellOro** [comment]
Die Hochschule stellt euch in den Pools Animate zur Verfügung.

**Comment by Ahornzweig** [comment]
Ich bin nicht in Furtwangen und die Anderen soweit ich weiß auch nicht.
Alternativ könnte man vielleicht auch das Bild austauschen, wenn es genau so ist wie das Alte. Aber dafür bräuchte man wahrscheinlich Photoshop.

**Comment by xcluu** [comment]
Habs über Eingabeaufforderung und Imagemagick komprimieren können. Neue Version ist hochgeladen. :)
