### ISSUE TITLE
Alte Videos blitzen auf

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#136]
wenn man von einer Animationsseite kommt...

**Comment by droda1** [comment]
Der Fehler war, dass wenn wir von einer Animationsseite gekomemn sind, wir die stopVideo() methode der youtube iframe api aufgerufen wurde. In der Dokumentation habe ich dann folgendes gefunden: " Diese Funktion ist für Ausnahmefälle gedacht, in denen du weißt, dass sich der Nutzer mit dem Player keine weiteren Videos ansehen wird." - Da wir immer wieder die selbe Instanz des Player Objekts verwenden müssen wir an dieser Stelle pauseVideo() benutzen. Hat das Problem gefixt.
