### ISSUE TITLE
7.10. I-Verkettung

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#139]
Hier gibt es bereits eine neue Interaktionsseite, korrekt?

**Comment by Ahornzweig** [comment]
Ja, dazu hatte ich in einem anderen Issue auch schon Feedback bekommen.
Muss noch verbessert werden.
https://ahornzweig.github.io/Projekt/Transformations/main.html

**Comment by JirkaDellOro** [comment]
dann kannst du die Issues als Duplikate markieren

**Comment by droda1** [comment]
duplicate -> closed

**Comment by JirkaDellOro** [comment]
Am Smartphone ist die unterste Transformation eingerückt, sollte auf gleicher Ebene sein.

**Comment by Ahornzweig** [comment]
fixed
