### ISSUE TITLE
9.8. Rasterisierung

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#153]
Zur Darstellung stehen 256 Rasterelemente zur Verfügung. Davon werden 19 genutzt. Was soll das?

Außerdem: der Vorgang sollte animiert werden, die 3D-Objekte also nach vorne auf die Projektionsebene geschoben und dabei abgeflacht werden, wo sie dann in die Rasterelemente überführt werden.

**Comment by HendrikLange** [comment]
fixed.
