### ISSUE TITLE
9.10. Raytracing

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#155]
Die Rückblende bei 0:33 ist lediglich verwirrend und macht den Eindruck eines Fehlers.

**Comment by HendrikLange** [comment]
fixed.

**Comment by JirkaDellOro** [comment]
Die Strahlauswahl ist suboptimal. Die erste Ablenkung ist kaum sichtbar, die zweite scheint den Raum schon gleich zu verlassen. Es wäre interessanter einen Strahl zu wählen, der nach Ablenkung das gelbe Mesh trifft und daher das weiße etwas gelblich einfärbt.
