### ISSUE TITLE
11.12. Boolean

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#170]
- die Schatten sind grausig
- das Highlight auf der Kugel ebenso
- zu Beginn sollten die beiden Objekt getrennt dargestellt werden und erst zusammengeschoben werden.
- eigene Farben verwenden für Objekt1, Objekt2 und Resultat!
- somit auch die Union darstellen

**Comment by HendrikLange** [comment]
Fixed
