### ISSUE TITLE
13.6. Kinematik

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#179]
0:40 die Bewegungen des Markers und des Gelenks gehen auseinander

**Comment by JirkaDellOro** [comment]
Bei inverser Kinematik sollte der Marker an der Hand dargestellt werden.

**Comment by JirkaDellOro** [comment]
Ich nehme an, die zweite Hälfte der Animation soll eigentlich zur interaktiven Seite (?)

**Comment by HendrikLange** [comment]
fixed
