### ISSUE TITLE
13.4 Bone animation - Interaktion

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#195]
https://ahornzweig.github.io/Projekt/BoneAnimation/main.html

Soll daran noch was verbessert werden?

**Comment by droda1** [comment]
@Ahornzweig 
Hier scheinen wir das selbe Problem wie bei #197 zu haben.

**Comment by Ahornzweig** [comment]
Hab die Videos auch hier komprimiert.
