### ISSUE TITLE
8.7 (I) Hierarchie

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#196]
https://ahornzweig.github.io/Projekt/Hierarchie/main.html

Ist das so in Ordnung?

**Comment by droda1** [comment]
@Ahornzweig 

Sieht erst mal ganz gut aus, leider sind die mp4 Files zu groß um sie auf github hosten zu können.
Lädt viel zu lange.
Kannst du vielleicht versuchen die mp4's in gifs zu konvertieren? vielleicht gewinnen wir so an Performance.

**Comment by droda1** [comment]
Bin hier von 2.08 Mb's auf bis zu 250Kbit runter gekommen:

https://ezgif.com/optimize/ezgif-1-e1a83bf0b141.gif

**Comment by Ahornzweig** [comment]
Hab die Videos komprimiert. Lädt jetzt schneller.
