### ISSUE TITLE
Zu verbessernde Sprechertexte sammeln

### ISSUE THREAD

**Issue by droda1** [JirkaDellOro/Computergrafik.Online#202]
Einige Sprechertexte haben noch Verbesserungspotential.
Es sollen hier alle Sprechertexte zusammengestellt werden, die Verbesserungsbedarf haben.

**Comment by HendrikLange** [comment]
[Sprechertexte und Infotexte Issues.docx](https://github.com/JirkaDellOro/Computergrafik.Online/files/4911936/Sprechertexte.und.Infotexte.Issues.docx)

Im Dokument sind alle inhaltlich zu verbessernde Sprechertexte und Infotexte angeführt. @JirkaDellOro @Ahornzweig @KevinBlumtritt @StfnMerdi @xcluu @droda1

**Comment by KevinBlumtritt** [comment]
Bei Kapitel 10.4 - "Phong Shading" muss der Sprechertext ebenfalls angepasst werden: "Kameraposition muss einbezogen werden um Reflektionen darzustellen"

**Comment by droda1** [comment]
Die beschriebenen Anforderungen der Story wurden erfüllt und das Dokument mit den gesammelten zu verbessernden Sprechertexten ist im issue angehangen. Ich packe das doc sicherheitshalber noch in das repository.
