### ISSUE TITLE
13.2 Interpolationskurven – Interaktion

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#226]
Hätte gerne noch etwas Feedback von @JirkaDellOro 

https://ahornzweig.github.io/Projekt/interpolationskurve/main.html

**Comment by JirkaDellOro** [comment]
Passt gut für mich. Bitte noch einen dünnen senkrechten Strich einbauen, der mit konstanter Geschwindigkeit durch das Diagramm läuft, am besten mit einem kleinen Punkt am Schnitt mit dem Graphen. Ansonsten werden viele Leute den Zusammenhang zwischen Diagramm und Bewegung nicht erkennen.

Bei mir ist das bewegte Objekt nur eine Ecke, soll das so sein?

**Comment by Ahornzweig** [comment]
Ich bin mir nicht ganz sicher, wie du das meinst. Könntest zu vielleicht eine kleine Skizze zeichnen?

**Comment by JirkaDellOro** [comment]
Ich versuche es erst noch einmal schriftlich. Wenn man "Start" klickt, wird die Animation abgespielt, und zwar bei konstantem Zeitverlauf von links nach rechts durch das Diagramm. Man sieht aber nur die "Ecke" fliegen, im Diagram tut sich nichts. Es ist wichtig, den Zeitpunkt auf seinem Weg durch das Diagramm beobachten zu können. Am einfachsten wohl durch den angesprochenen senkrechten Strich, gerne noch mit einem fetteren Punkt am Schnitt mit dem Graphen.

**Comment by Ahornzweig** [comment]
Ich denke ich habe es jetzt verstanden.
Ich habe erstmal nur den Strich umgesetzt. Falls ich am Ende noch Zeit habe, versuche ich mich auch an dem Punkt.
