### ISSUE TITLE
7.1 Aufbau von Vektoren: Interaktion REVISITED

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#238]
Ich habe eine neue Version der Interaktion ohne Animate erstellt.
Hätte jetzt gerne etwas Feedback von @JirkaDellOro 
https://ahornzweig.github.io/Projekt/AufbauVektoren/main.html

**Comment by JirkaDellOro** [comment]
Es wäre noch schön, wenn die Interaktionselemente sich den aktuellen Werten anpassen, wenn man die Figur wechselt, anstatt das die Figurwerte sich dabei sprunghaft ändern

**Comment by Ahornzweig** [comment]
Habe die Interaktion entsprechend angepasst.
