### ISSUE TITLE
1.5 (I) Zahlensysteme

### ISSUE THREAD

**Issue by sailerco** [JirkaDellOro/Computergrafik.Online#297]
Technisch sind mir keine Fehler aufgefallen. Ich habe aber trotzdem ein paar kleine Verbesserungsvorschläge:

1. Auf größeren Bildschirmen könnte die Darstellung etwas größer skaliert sein (Werte über dem Binärsystem schwer zu lesen). Am Handy und Laptop ist es aber gut lesbar.
2. Der Abstand zwischen den Zwischenüberschrift (…system) und den dazugehörigen Zahlenwerten ist etwas zu groß. Es wirkt so als gehören sie nicht zusammen. Dafür ist der Abstand zwischen den "Zahlenwerten von dem Dezimalsystem" und der Überschrift „Binärsystem“ zu klein.
3. Der Schieberegler ist okay, aber manchmal ist es schwer auf einen bestimmten Wert zu kommen.

**Comment by JirkaDellOro** [comment]
Bitte schreibe bei den Issues immer Kapitel- und Seitennummer vornedran, wie gehabt.
