### ISSUE TITLE
Webdesign von Videoseiten ändern

### ISSUE THREAD

**Issue by StfnMerdi** [JirkaDellOro/Computergrafik.Online#59]
Seiten mit Videos wirken noch bisschen zu minimalistisch. Wirkt wie Youtube Channel.
Design ändern oder andere Ideen??

**Comment by droda1** [comment]
Hey Stefan, ich würde die Art die Videos darzustellen erst mal so lassen,
da wir andere Aufgaben fertigstellen müssen, die momentan eine höhere Priorität haben,
wie beispielsweise die Fertigstellung des Contents und die Entwicklung einer Wissensabfrage(Quiz).

Was sagen sie dazu @JirkaDellOro ?

**Comment by StfnMerdi** [comment]
Ja, bin ich ganz deiner Meinung. Issue ist jetzt auch etwas älter und die Prioritäten haben sich auch geändert.

Falls wir noch Zeit haben, könnte wir das berücksichtigen.

**Comment by droda1** [comment]
Würde das Issue dann erst mal schließen, können es ja wieder öffnen wenn wir die Kapazitäten haben.

**Comment by JirkaDellOro** [comment]
Prioritäten
1. Vollständigkeit
2. Funktion
3. Alles andere
