### ISSUE TITLE
Informationen

### ISSUE THREAD

**Issue by KevinBlumtritt** [JirkaDellOro/Computergrafik.Online#61]
Problem mit Platzierung der Informationen während der Videos (rechte Seite des Bildschirms). Könnten leicht übersehen werden.

**Comment by droda1** [comment]
@KevinBlumtritt würde das erst mal so lassen (zumindest auf Desktop), mobile wollten wir eventuell noch über Anpassungen diskutieren.

**Comment by droda1** [comment]
@JirkaDellOro ich finde die Informationsleiste an der Seite prinzipiell nicht schlecht aber vielleicht können wir einfach noch zusätzlich die Möglichkeit anbieten, diese ein und auszuklappen, ähnlich wie bei der mobile version.

**Comment by JirkaDellOro** [comment]
Wenn Sie standardmäßig sichtbar ist und man sie wegklappen kann, wäre das für mich in Ordnung. Allerdings halte ich es nicht für erforderlich und sehe keinen Sinn darin, hierfür weitere Interaktionselemente zu entwickeln.

**Comment by droda1** [comment]
@JirkaDellOro alles klar, dann würde ich das erst mal hinten anstellen und das issue hier closen, können dann ja immer noch ein neues anlegen, wenn der bedarf noch besteht. Wäre das in Ordnung?
