### ISSUE TITLE
Einbindung der Interaktiven Seiten mit Pages

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#62]
Die Buttons auf den Interaktiven seiten führen teilweise zu nichts (bei der Pages Version).

Beispiel: ( I ) Farbtiefe 16/24 Bit in Rastergrafik und Farbtiefe

**Comment by JirkaDellOro** [comment]
Falls das Problem nur mit Pages auftritt sollten wir prüfen, ob hier serverseitige Software genutzt wird, die auf Pages nicht lauffähig ist. Das sollte nicht sein und ich danke auch nicht, dass es so ist. Das könnt ihr bei einem Treffen mit Benedikt ggf. ansprechen

**Comment by droda1** [comment]
Gibts da schon irgendwelche Findings dazu ?

**Comment by droda1** [comment]
Habe die bis jetzt vorhandenen Interaktionen eingebunden und die toten links verbessert.
Zusätzlich habe ich ein weiters issue angelgt für in zukunft fertiggestellte Interaktionen und upgedatete Interaktionen:
https://github.com/JirkaDellOro/Computergrafik.Online/issues/84

**Comment by JirkaDellOro** [comment]
Dann macht mal
