### ISSUE TITLE
Roboter shade ist flat

### ISSUE THREAD

**Issue by HendrikLange** [JirkaDellOro/Computergrafik.Online#64]
Der Roboter ist auf den Renderings flat shaded. Würde smooth eventuell besser aussehen. :)

**Comment by JirkaDellOro** [comment]
Gut möglich, dass es Absicht ist um den Aufbau aus einzelnen Flächen sichtbar zu machen

**Comment by droda1** [comment]
@HendrikLange wie ist hier der Status? Lassen wir den flatshade so wie er ist ?

**Comment by HendrikLange** [comment]
Ja lassen wir so.
