### ISSUE TITLE
techonological onboarding

### ISSUE THREAD

**Issue by droda1** [JirkaDellOro/Computergrafik.Online#65]
Due to the unconventional technologystack we need to have a introduction for the current implementation and the used technologies.

**Comment by benediktgrether** [comment]
Hi, 
i have time to talk about the implementation and used technologies 
- Monday from 10.00 till 14.00
- Tuesday from 10.00 till 15.00
- Wednesday from 10.00 till 14.00   
- Thursday from 11.15 till 14.00

**Comment by droda1** [comment]
Hi Benedikt,
Thank you for your reply. 
Are you available on Monday the 4th Novembre from 13:00 till14:00?
That would be really nice.

**Comment by benediktgrether** [comment]
Hy droda,
I'm available on Monday. 
Where can we meet?

**Comment by droda1** [comment]
Sorry for the delayed reply,
Let's meet in the L-Bau, im sure there will be some room for us.
So at 13:00 at the L-Bau?

**Comment by benediktgrether** [comment]
Ok. Let's meet in front of the L-Bau and go together inside. I'm wearing a blue beanie.

**Comment by JirkaDellOro** [comment]
Bin gespannt ob ihr dann weiter auf Englisch kommuniziert....

**Comment by droda1** [comment]
Dank des Treffens mit Benedikts haben wir nun einen besseren Überblick über die aktuelle Rahmenimplementierung erlangt, noch bestehende bugs aufgenommen und sind zu dem Fazit gekommen, dass viele Module und Abhängigkeiten redundant sind und vieles unschön eingebunden ist.
Daher sollte meiner Meinung nach Zeit in die Neuimplementierung des Rahmens(bevorzugt mit Bootstrap 4) investiert werden.
Dieses Issue sehe ich hiermit als Done an.
