### ISSUE TITLE
Unterschied zwischen low/high poly und Subdivision?

### ISSUE THREAD

**Issue by xcluu** [JirkaDellOro/Computergrafik.Online#66]
Ich bin auf ein Problem gestoßen, und zwar weiß ich nicht wie ich die interaktive Seite von low/high poly umsetzen soll. Kann ich dafür einfach Subdivison benutzen, oder wie sollte das sonst umsetzbar sein? Ich frage, da sich schon eine andere interaktive Seite mit Subdivision beschäftigt. Danke!

**Comment by JirkaDellOro** [comment]
Ich nehme an Du meinst Kapitel 11 Abschnitt 3. Wenn Du mit Subdivision gute Ergebnisse erzielst, kannst Du das nutzen. Ich denke, dass die Interaktion ein Bild aus einer Folge von Bildern mit ab- bzw. zunehmender Polygonzahl zeigt. So hast Du Kontrolle über das Ergebnis.

**Comment by xcluu** [comment]
Okay, dann werde ich das so versuchen. Danke für die schnelle Antwort.
