### ISSUE TITLE
Termine

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#67]
Da wir weder einen Dienstag- noch Donnerstag-Termin finden konnten, mussten wir auf den Mittwoch ausweichen. Dieser wird aber immer wieder für Gremienarbeiten genutzt. 

So am nächsten Mittwoch (30.10.19) ab 15.00 Uhr. Wir können uns gerne um 14.00 Uhr treffen und ich gehe früher raus.

Am Mittwoch darauf (7.11.19) klappt es bei mir gar nicht. 

Bei Fragen weiter Issues posten, Gesprächsbedarf kurzfristig bitte mit mir abstimmen.

Bitte schreibt in diesem Post noch einmal, welche Veranstaltungen den Dienstag bzw. Donnerstag für euch blockieren.

**Comment by HendrikLange** [comment]
Bei MK ist es Dienstags 11:30 -13:00 Ideenentwicklung & Donnerstags 15:45 -17:15 Konzeption
