### ISSUE TITLE
7.2 Unterschied zu Rastergrafiken – Interaktion

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#70]
Ich habe eine Frage zu diesem Modul.

Ist es ausreichend, wenn man an die zwei Bilder heran zoomt, oder soll noch mehr geschehen?
Im Drehbuch steht noch etwas von "auseinander bauen".

**Comment by JirkaDellOro** [comment]
Das "auseinanderbauen" ist ein Relikt einer früheren Version des Drehbuchs, wurde verworfen und sollte eigentlich gelöscht sein. Mit dem Schieberegler heranzoomen, so dass man bei der Rastergrafik mehr und mehr die einzelnen Pixel erkennt während die Vektorgrafik immer fein aufgelöst bleibt, genügt.

**Comment by Ahornzweig** [comment]
Okay, vielen Dank :)
Dann werde ich das erstmal mit Typescript umsetzen.
