### ISSUE TITLE
7. Vektorgrafik : ( I ) Aufbau von Vektoren Fertigstellen

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#72]

**Comment by Ahornzweig** [comment]
Ich habe eine Frage zu Animate. Ist es möglich die Farbe einer Instanz über JS zu ändern?
ich habe bis jetzt keine funktionierende Lösung gefunden.

**Comment by JirkaDellOro** [comment]
Da gibt es verschiedene Ansätze, das müssten wir uns im Detail anschauen. Ich kann auch nicht sicher sagen, was im HTML5-Mode alles möglich ist. Dienstag im 4. Block habe ich Zeit.

**Comment by Ahornzweig** [comment]
Danke für die Hilfe.
Inzwischen habe ich das Problem aber gelöst.
Ich habe die Grundfarbe als einzelne Elemente erstellt und dann miteinander addiert. Über Alpha konnte ich dann die Farben ändern.

**Comment by droda1** [comment]
@Ahornzweig kann das Issue geschlossen werden?
