### ISSUE TITLE
Review Modeling Videos

### ISSUE THREAD

**Issue by HendrikLange** [JirkaDellOro/Computergrafik.Online#75]
Habe nun die fertigen Videos aus Lektion 11 (Modeling) sowie 12.04 "UV-Mapping" hochgeladen. 

Sofern Änderungsbedarf an den Videos besteht können wir dies bei der nächsten Sitzung besprechen.

**Comment by JirkaDellOro** [comment]
Hochgeladen wo?

**Comment by HendrikLange** [comment]
Verzeihung, hier die Links zu den GitHub Verzeichnissen

https://github.com/JirkaDellOro/Computergrafik.Online/tree/master/mp4%20Videos/11-Modeling

https://github.com/JirkaDellOro/Computergrafik.Online/tree/master/mp4%20Videos/12-Texturen/1204
