### ISSUE TITLE
7.5 Verkettung – Interaktion

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#80]

**Comment by Ahornzweig** [comment]
@JirkaDellOro ich hätte gern etwas Feedback, ob die Interaktion soweit gut ist.

https://ahornzweig.github.io/Projekt/Transformations/main.html

**Comment by JirkaDellOro** [comment]
Im Groben schon ganz gut, folgendes sollte verändert werden.
- die Interaktionsmöglichkeit zum Tausch sollte zwischen den Headlines stehen, da genügt dann ein "Tausch"-Button ohne Richtungsunterscheidung
- Es sollte einen Reset-Button geben, die alle Transformationen neutralisiert
- Es sollte ein Grid im Hintergrund geben, an dem man sich orientieren kann

**Comment by Ahornzweig** [comment]
@JirkaDellOro ich hab die Interaktion überarbeitet.
Passt es jetzt?
https://ahornzweig.github.io/Projekt/Transformations/main.html

**Comment by JirkaDellOro** [comment]
Leider nein.

- Die Buttons zum Tausch sollen zwischen den Headlines stehen und zwar an fester Position. Jetzt sind sie Teil der Headlines, was die Interaktion deutlich erschwert.
- Die Verkettung ist noch nicht richtig berechnet. Vergleiche https://webuser.hs-furtwangen.de/~del/Apps/Transformation/Transformation.html
- Sollte die Skalierung nicht auch dabei sein?

**Comment by Ahornzweig** [comment]
Ich weiß leider nicht, was bei der Verkettung falsch ist.  Ist es die Rotation? Die sieht etwas anders aus.
Das Konzept sieht eigentlich gar keine Translation vor, das war mein Fehler. Soll ich sie durch die Skalierung ersetzen oder die Skalierung hinzufügen?

**Comment by JirkaDellOro** [comment]
Wenn Du es richtig codest, kommt auch zwangsläufig das richtige raus. Verkette also schlicht die Transformationen wie erforderlich. Die Translation sollte drinbleiben, eher nehmen wir die Scherung raus, da sie einen seltenen Sonderfall darstellt.

**Comment by Ahornzweig** [comment]
Als ich gerade nochmal drüber geschaut habe, hab ich bemerkt, dass ich die Rotation doppelt an die Transformation dranhänge.
Hab es auch neu gepusht: https://ahornzweig.github.io/Projekt/Transformations/main.html
An sich setze ich über das TS den Transform Style immer neu. An sich sollte das korrekt sein, oder?

![image](https://user-images.githubusercontent.com/43846334/90266897-04a91e00-de55-11ea-94c3-69a7d1a9a2f5.png)

**Comment by JirkaDellOro** [comment]
jetzt scheint es zu passen

**Comment by Ahornzweig** [comment]
Hab die anderen Verbesserungsvorschläge auch umgesetzt, hoffe es passt jetzt :D
https://ahornzweig.github.io/Projekt/Transformations/main.html
