### ISSUE TITLE
7.6 Rasterung von Vektrografiken – Interaktion

### ISSUE THREAD

**Issue by Ahornzweig** [JirkaDellOro/Computergrafik.Online#87]
Die Interaktion ist an sich fertig.
Kann @JirkaDellOro bitte einmal drüber schauen?

Um einen Punkt zu verschieben, muss man auf einem Punkt die linke Maustaste gedrückt halten.
Das größte Problem ist, dass man die Maus nicht zu schnell bewegen darf. 

https://ahornzweig.github.io/Projekt/070602/Test/index.html

**Comment by JirkaDellOro** [comment]
Das passt schon recht gut und das Problem mit einer schnellen Mausbewegung konnte ich nicht nachvollziehen.  Allerdings gibt es ein anderes:

pixelated vs. auto ist nur die halbe Lösung. Der Browser rendert dann vergrößerte einzelne Pixel nicht mit Verlauf sondern vollflächig. Die Farbzwischenstufen des Antialiasing werden aber immer noch erzeugt!

Ich habe etwas recherchiert und eine Lösung gefunden, die SVG-Filter nutzt. Daraus habe ich dir ein Beispiel gebastelt. Siehe
https://www.w3schools.com/code/tryit.asp?filename=GDWSDB5JXQZB

Entferne den Doppelslash unten im Code um die Wirkung des Filters zu erkennen.

PS: in deiner Anwendung solltest Du auch die Auflösung noch weiter runterschrauben, so dass man die einzelnen Pixel gut sieht, so wie in meinem Beispiel

**Comment by Ahornzweig** [comment]
Ich habe es angepasst. Ist es so okay?

https://ahornzweig.github.io/Projekt/070602/Test/index.html

**Comment by JirkaDellOro** [comment]
Nimm das auto ganz raus und bleibe bei pixelated, sonst sehen wir das Sub-Pixel-Rendering, was wieder ein anderes Verfahren ist.

**Comment by Ahornzweig** [comment]
Okay, mach ich.

**Comment by JirkaDellOro** [comment]
Kann der Issue geschlossen werden?

**Comment by Ahornzweig** [comment]
Ich denke schon.
