### ISSUE TITLE
Videoskalierung

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#90]
Das Video soll in Breite oder Höhe standardmäßig den verfügbaren Platz einnehmen

**Comment by droda1** [comment]
Selbstverständlich kann ich den Player größer machen so,  dass er die volle Breite einnimt.
Das Video wird dadurch allerdings nicht größer, was jedoch am Video liegt und nicht am Player.
Wir haben ein 1:1 Format, so dass ein padding erforderlich ist und es nicht in die breite skaliert.

**Comment by JirkaDellOro** [comment]
Ich gehen davon aus, dass Video skalierbar ist.

**Comment by droda1** [comment]
@JirkaDellOro die changes sind jetzt deployed. können sie vielleicht mal nachsehen ob das nun so passt?

**Comment by JirkaDellOro** [comment]
Hatte ich da nicht schon drauf geantwortet? Was ist die jüngste Entwicklung?

**Comment by droda1** [comment]
Habe das Videofenster angepasst, es ist nun wesentlich größer.

**Comment by droda1** [comment]
Ah tut mir Leid, habe das Comment in dem anderen issue nicht gesehen :)

**Comment by JirkaDellOro** [comment]
"Watche" dieses Repository, dann entgeht dir nichts!
