### ISSUE TITLE
Informationsleiste

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#97]
Funktioniert nur sehr sporadisch und kann mit der Videonavigation nicht umgehen.

**Comment by droda1** [comment]
Ich habe die Funktionalität überprüft, es liegt daran, dass die Informationen einfach noch nicht eingefügt sind.
Somit müssen wir einfach nur das data.json an den entsprechenden stellen mit den bullet points befüllen, die da an dem entsprechenden Zeitpunkt erscheinen sollen.

**Comment by droda1** [comment]
habe hier ein folge issue erstellt: https://github.com/JirkaDellOro/Computergrafik.Online/issues/204
