### ISSUE TITLE
1.7. Maßeinheiten

### ISSUE THREAD

**Issue by JirkaDellOro** [JirkaDellOro/Computergrafik.Online#99]
Im Video 0:58 steht ein überflüssiger Doppelpunkt

**Comment by JirkaDellOro** [comment]
Heißt es nicht Mebibyte?

**Comment by JirkaDellOro** [comment]
Infotext: Verewendung ist kein deutsches Wort

**Comment by droda1** [comment]
Ich erstelle noch ein Issue, um generell den info text aller videos zu überarbeiten.

**Comment by droda1** [comment]
wurde entsprechend angepasst.
